version: '3'
services: 
    master:
        image: redis
        container_name: redis-master
        command: redis-server --requirepass 123456 --masterauth 123456
        ports: 
            - 6380:6379
    
    slave1:
        image: redis
        container_name: redis-slave-1
        command: redis-server --slaveof redis-master 6379 --requirepass 123456 --masterauth 123456
        ports: 
            - 6381:6379

    slave2:
        image: redis
        container_name: redis-slave-2
        command: redis-server --slaveof redis-master 6379 --requirepass 123456 --masterauth 123456
        ports: 
            - 6382:6379