version: "3"
services:
    redis-persist-demo:
        image: redis
        container_name: redis
        ports:
            - 6380:6379
        command: redis-server /usr/local/etc/redis/redis.conf
        volumes:
            - ./redis_config/redis.conf:/usr/local/etc/redis/redis.conf
            - ./redis_data/:/data/